before_script: cd recipes_api
language: python
python:
  - "3.10.0"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"