# Generated by Django 3.1.7 on 2021-02-27 01:53

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210225_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=recipe.models.get_recipe_filepath),
        ),
    ]
